export const weatherActionTypes = {
  INITIALIZE_DATA: "INITIALIZE_DATA",
  SAVE_WEATHER_DATA: "SAVE_WEATHER_DATA",
  LOCATION_ACCESS_DENIED: "LOCATION_ACCESS_DENIED",
  FETCH_CITY_WEATHER: "FETCH_CITY_WEATHER",
  FETCH_CITY_WEATHER_ERROR: "FETCH_CITY_WEATHER_ERROR",
};
